name: OCI Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: Run a multi-line script
        run: |
          digest=$(sha256sum ./oras-archive.tar | awk -F ' ' '{print $1}')
          digest=sha256:$digest
          echo $digest
          BLOB_BODY=$(xxd -b ./oras-archive.tar)
          FILENAME=/home/heiko/dummy/packages.txt
          BLOB_LENGTH=$(stat -c%s ./oras-archive.tar)
          curl -i -s -k \
          -H "Authorization: Bearer `echo $GIHUB_TOKEN`" \
          -H "Content-Type: application/octet-stream" \
          -H "Content-Length: $BLOB_LENGTH" \
          -X PUT "https://ghcr.io/srahul3?digest=$digest" \
          -d "$BLOB_BODY"
