name: Publish OCI Image using API

on: 
  workflow_dispatch:
  
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  updateSubClaim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create archive
        run: |
          wdir=$(pwd)
          cd /tmp
          tar -czvf release.tar.gz ${wdir}          
          cd ${wdir}          
          echo "$(pwd)"
      - name: verify
        run: |
          pwd          
          cd /tmp
          ls -ltr | grep tar.gz
      - name: API Publish
        run: |
          curl --request POST \
          --url http://api.github.localhost/repos/${{ github.repository }}/actions/package \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/octet-stream' \
          --data-binary "@/tmp/release.tar.gz" \
          --fail
