name: Publish OCI Image using API

on: 
  workflow_dispatch:

jobs:
  updateSubClaim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create archive
        run: |
          echo "$(pwd)"
          cd ..
          echo "$(pwd)"
          echo "$(ls -ltr)"
      - name: Publish
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/actions/package
          owner: "a"
          repo: "b"
          use_default: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # echo "Default Opt Status : ${{ fromJson(steps.get_updated_opt_status.outputs.data).use_default }}"
