name: Publish OCI Image using API

on: 
  workflow_dispatch:

jobs:
  updateSubClaim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create archive
        run: |
          wdir=$(pwd)
          cd /tmp
          tar -czvf release.tar.gz ${wdir}          
          cd ${wdir}          
          echo "$(pwd)"
      - name: verify
        run: |
          pwd          
          cd /tmp
          ls -ltr | grep tar.gz
      - name: API Publish
        run: |
          response=$(curl -sb -X POST "https://api.github.com/repos/srahul3/oci-image-sdk/actions/package" -H "Authorization: bearer ${{ secrets.PAT }}" -H "Content-Type: application/octet-stream" -H "tag: 1.0.2-multilayeraction" --data-binary "@/tmp/release.tar.gz")
          echo $(response)
