name: OCI Publish2
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          PAT_READ_WRITE=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
          digest=$(echo -n echo -n foobar | sha256sum | awk -F ' ' '{print $1}')
          digest=sha256:$digest
          echo $digest
          curl -i -k -f \
          -H "Authorization: Bearer `echo $GIHUB_TOKEN`" \
          -X POST https://ghcr.io/v2/srahul3/foobar/blobs/uploads/
          
      - name: Run a multi-line script
        run: |
          PAT_READ_WRITE=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
          digest=$(echo -n echo -n foobar | sha256sum | awk -F ' ' '{print $1}')
          digest=sha256:$digest
          echo $digest
          curl -i -k -f \
          -H "Authorization: Bearer `echo $PAT_READ_WRITE | base64`" \
          -X POST https://ghcr.io/v2/srahul3/foobar/blobs/uploads/
          
      - name: Run a multi-line script
        run: |
          sha=$(sha256sum ./oras-archive.tar | awk -F ' ' '{print $1}')
          digest=sha256:$sha
          echo $digest
          echo "https://ghcr.io/v2/srahul3/foobar/blobs/uploads/$sha"
          BLOB_LENGTH=$(stat -c%s ./oras-archive.tar)
          curl -i -s -k \
          -H "Authorization: Bearer `echo $GIHUB_TOKEN`" \
          -H "Content-Type: application/octet-stream" \
          -H "Content-Length: $BLOB_LENGTH" \
          -d @oras-archive.tar \
          -X PATCH -D - -o /dev/null -s \
          https://ghcr.io/v2/srahul3/foobar/blobs/uploads/$sha
      
      - name: list all blobs
        run: |
          curl -i -s -k \
          -H "Authorization: Bearer `echo $GIHUB_TOKEN`" \
          -X GET -D - -o /dev/null -s \
          https://ghcr.io/v2/_catalog
