name: OCI Publish2
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: Run a multi-line script
        run: |
          digest=$(sha256sum ./oras-archive.tar | awk -F ' ' '{print $1}')
          digest=sha256:$digest
          echo $digest
          curl -i -s -k \
          -H "Authorization: Bearer `echo $GIHUB_TOKEN`" \
          -X POST -D - -o /dev/null -s \
          https://ghcr.io/v2/srahul3/hello/blobs/uploads/
