
name: OCI Publish-basic
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          TOKEN1=$(curl -Ls -u x-oauth-token:$GITHUB_TOKEN 'https://ghcr.io/token?scope=repository:srahul3/oci-image-sdk:pull,push' | jq -r .token)
          TOKEN=$(curl --silent https://ghcr.io/token\?scope\=repository:srahul3/oci-image-sdk:pull,push | jq -r .token)
          digest=$(echo -n echo -n foobar | sha256sum | awk -F ' ' '{print $1}')
          digest=sha256:$digest
          echo $digest
          curl -i -k \
          -H "Authorization: Bearer $TOKEN1" \
          -X POST https://ghcr.io/v2/srahul3/oci-image-sdk/blobs/uploads/
