name: Artifcat upload
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}          
      
      - name: Use URL for something
        run: echo "${{github.run_id}}"
    
      - name: curl
        run: |
          curl "https://api.github.com/repos/srahul3/oci-image-sdk/actions/artifacts" -s \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}"

      - name: curl
        run: |
          curl "https://api.github.com/repos/srahul3/oci-image-sdk/actions/runs/${{github.run_id}}/artifacts" \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}"

